version: '3.1'

services:

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      
volumes:
  dbdata:
